ansible_python_interpreter: /usr/bin/python3
base_python_package: 'python3'

apt_update_cache: yes

app_name: commcare_connect
app_user: connect
home_dir: /home/{{ app_user }}
app_group: webapps
project_name: commcare-connect
base_dir: '{{home_dir}}/www'
project_dir: '{{ base_dir }}/{{ project_name }}'
src_dir: '{{ base_dir }}/{{ project_name }}/code_root'
log_dir: '{{ base_dir }}/log'

git_repo: https://github.com/dimagi/commcare-connect.git
git_branch: sk/deploy
