servers:
  web:
    hosts:
      - 54.91.53.131
    options:
      # create by ansible
      env-file: '/home/connect/www/commcare-connect/docker.env'
  celery:
    hosts:
      - 44.193.193.67
    options:
      # create by ansible
      env-file: '/home/connect/www/commcare-connect/docker.env'
    cmd: /start_celery
    labels:
      traefik.enable: false
