servers:
  web:
    hosts:
      - 54.146.23.50
    options:
      # create by ansible
      env-file: '/home/connect/www/commcare-connect/docker.env'
  celery:
    hosts:
      - 54.146.23.50
    options:
      # create by ansible
      env-file: '/home/connect/www/commcare-connect/docker.env'
    cmd: /start_celery
    labels:
      traefik.enable: false
