service: commcare-connect

image: commcare-connect

servers:
  web:
    hosts:
      - ec2-3-90-216-194.compute-1.amazonaws.com
    options:
      # create by ansible
      env-file: '/home/connect/www/commcare-connect/docker.env'
  celery:
    hosts:
      - ec2-3-90-216-194.compute-1.amazonaws.com
    options:
      # create by ansible
      env-file: '/home/connect/www/commcare-connect/docker.env'
    cmd: /start_celery
    labels:
      traefik.enable: false

healthcheck:
  path: /
  port: 8000
  max_attempts: 10
  interval: 20s

ssh:
  user: connect

logging:
  driver: awslogs
  options:
    awslogs-region: 'us-east-1'
    awslogs-group: 'commcare-connect'

builder:
  multiarch: false
  dockerfile: '../Dockerfile'
  context: '../'

registry:
  server: 037129986032.dkr.ecr.us-east-1.amazonaws.com
  username: AWS
  password: <%= %x(./registry_password.sh) %>
