service: commcare-connect

image: commcare-connect

servers:
  web:
    hosts:
      - 3.90.216.194
    options:
      env-file: '/home/connect/www/commcare-connect/docker.env'

healthcheck:
  path: /
  port: 8000
  max_attempts: 7
  interval: 20s

ssh:
  user: connect

logging:
  driver: awslogs
  options:
    awslogs-region: 'us-east-1'
    awslogs-group: 'commcare-connect'

builder:
  multiarch: false
  dockerfile: '../Dockerfile'
  context: '../'

registry:
  server: 037129986032.dkr.ecr.us-east-1.amazonaws.com
  username: AWS
  password: <%= %x(aws ecr get-login-password --region=us-east-1 --profile "${AWS_PROFILE:-connect-staging}") %>
