webservers:
  hosts:
    web0:
      ansible_host: 54.158.97.180
    celery0:
      ansible_host: 44.193.193.67
  vars:
    ansible_user: ubuntu
    secrets_file: 'Ansible Secrets - Production'
    commcare_hq_url: 'https://www.commcarehq.org'
    sentry_environment: 'production'
