---
- name: Create Docker Env
  template:
    src: 'docker.env.j2'
    dest: '{{ docker_env_file }}'
    owner: '{{ app_user }}'
    group: '{{ app_group }}'
    mode: 0644
  tags:
    - deploy

- name: Build Docker image
  community.docker.docker_image:
    name: '{{ docker_image_name }}'
    build:
      path: '{{ src_dir }}'
      dockerfile: '{{ dockerfile }}'
    source: build
    state: present
  tags:
    - deploy

- name: Create containers
  community.docker.docker_container:
    name: '{{ docker_container_name }}'
    image: '{{ docker_image_name }}'
    env_file: '{{ docker_env_file }}'
    state: started
  tags:
    - deploy
