name: Deploy

env:
  AWS_REGION: 'us-east-1'

permissions:
  id-token: write
  contents: read

on:
  #  workflow_run:
  #    workflows: [CI]
  #    types: [completed]
  #    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: 'C05APTXCTSM'
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                      "type": "mrkdwn",
                      "text": "*CommCare Connect Deploy*"
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "section",
                  "text": {
                      "type": "mrkdwn",
                      "text": "*Status*: In Progress"
                  }
                },
                {
                  "type": "context",
                  "elements": [
                      {
                          "type": "mrkdwn",
                          "text": "<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Deploy Run>"
                      }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN}}
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2.2.0
        with:
          role-to-assume: arn:aws:iam::037129986032:role/github_deploy
          role-session-name: GithubDeploy
          aws-region: ${{ env.AWS_REGION }}

      - name: Set Version Label
        run: echo "version_label=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV

      - id: deploy
        name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ env.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws_session_token: ${{ env.AWS_SESSION_TOKEN }}
          application_name: commcare-connect
          environment_name: Commcare-connect-env
          version_description: ${{ github.sha }}
          version_label: ${{ env.version_label }}
          region: ${{ env.AWS_REGION }}
          deployment_package: deploy.zip
          wait_for_environment_recovery: 120

      - uses: slackapi/slack-github-action@v1.24.0
        if: always()
        with:
          channel-id: 'C05APTXCTSM'
          update-ts: ${{ steps.slack.outputs.ts }}
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                      "type": "mrkdwn",
                      "text": "*CommCare Connect Deploy*"
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "section",
                  "text": {
                      "type": "mrkdwn",
                      "text": "*Status*: ${{ steps.deploy.conclusion }}"
                  }
                },
                {
                  "type": "context",
                  "elements": [
                      {
                          "type": "mrkdwn",
                          "text": "<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Deploy Run>"
                      }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN}}
